/* ============================================================
   GASTA LA PLATA DE ELON — Datos
   ------------------------------------------------------------
   Todas las cifras son APROXIMADAS y con fines satíricos/
   educativos. Fuentes públicas (prensa económica, precios de
   lista, estimaciones de organismos). Última actualización a
   mano: junio 2026. Cámbialas en este archivo cuando quieras.
   ============================================================ */

// --- La fortuna ---------------------------------------------------
// Elon Musk: el PRIMER trillonario de la historia.
// (En inglés "trillion" = 1 millón de millones = 1,000,000,000,000.
//  En español formal eso es "un billón". Aquí usamos "trillonario"
//  como lo llama la prensa popular.)
const NET_WORTH = 1_000_000_000_000; // 1 millón de millones de USD 🤯

// ¿Cuánto "gana" por segundo?
// Calibrado para que su ingreso POR MINUTO sea exactamente 827 veces
// el sueldo MENSUAL promedio en Perú (~$460):
//   827 * 460 / 60 s ≈ 6,340 USD/s  →  $380,520 por minuto.
const EARN_PER_SECOND = 6342;

// Años que trabaja una persona promedio en toda su vida (~de los 25 a los 65).
// Sirve para calcular cuánto gana alguien en TODA su vida laboral.
const WORKING_YEARS = 40;

// --- Sueldos promedio mensuales (aprox, en USD) ------------------
// Para poner las cifras en perspectiva humana.
const SALARIES = [
  { pais: "🇵🇪 Perú",      local: "S/ 1,700",        usd: 460 },
  { pais: "🇨🇴 Colombia",  local: "$1,800,000 COP",  usd: 450 },
  { pais: "🇲🇽 México",    local: "$15,000 MXN",     usd: 830 },
  { pais: "🇦🇷 Argentina", local: "$650,000 ARS",    usd: 600 },
  { pais: "🇨🇱 Chile",     local: "$700,000 CLP",    usd: 740 },
  { pais: "🇧🇴 Bolivia",   local: "Bs 2,750",        usd: 400 },
];

// --- Catálogo de "compras" --------------------------------------
// price siempre en USD.
const CATEGORIES = [
  {
    id: "antojos",
    title: "Gadgets y antojitos",
    emoji: "🎮",
    blurb: "Lo que un humano normal ahorra meses para comprar. Para él, redondeo.",
    items: [
      { id: "bigmac",   emoji: "🍔", name: "Un Big Mac",            price: 5,     note: "El famoso Índice Big Mac. Para él, ni una migaja." },
      { id: "iphone",   emoji: "📱", name: "iPhone 17 Pro Max",     price: 1199,  note: "El celular que todos quieren y casi nadie necesita." },
      { id: "airpods",  emoji: "🎧", name: "AirPods Pro 3",         price: 249,   note: "Para no escuchar los problemas del mundo." },
      { id: "switch2",  emoji: "🎮", name: "Nintendo Switch 2",     price: 449,   note: "Mario nunca tuvo tanta plata y es más feliz." },
      { id: "ps5",      emoji: "🕹️", name: "PlayStation 5 Pro",     price: 699,   note: "Para distraerte de que él compró el planeta." },
      { id: "mbp",      emoji: "💻", name: "MacBook Pro 16\"",      price: 2499,  note: "Para escribir tu tesis sobre la desigualdad." },
      { id: "mba",      emoji: "💻", name: "MacBook Air",           price: 999,   note: "La 'barata'. Cuesta dos sueldos peruanos." },
      { id: "vision",   emoji: "🥽", name: "Apple Vision Pro",      price: 3499,  note: "Para ver un metaverso que nadie pidió." },
      { id: "jordans",  emoji: "👟", name: "Zapatillas Jordan (edición limitada)", price: 400, note: "Para correr... es un decir." },
      { id: "dji",      emoji: "🚁", name: "Un dron DJI tope de gama", price: 2500, note: "Para mirar el mundo desde arriba, como él." },
    ],
  },
  {
    id: "lujo",
    title: "Lujo absurdo",
    emoji: "🏎️",
    blurb: "Aquí ya no compras cosas, compras maneras de presumir.",
    items: [
      { id: "tesla",    emoji: "🚗", name: "Tesla Model S Plaid",        price: 90000,     note: "Su propio carro. En efectivo, claro." },
      { id: "ferrari",  emoji: "🏎️", name: "Ferrari Roma",               price: 250000,    note: "0 a 100 km/h en 3.4s. La pobreza no corre tan rápido." },
      { id: "lambo",    emoji: "🏎️", name: "Lamborghini Huracán",        price: 250000,    note: "Unos 45 años de sueldo de un peruano. Por un carro." },
      { id: "birkin",   emoji: "👜", name: "Bolso Birkin de Hermès",     price: 25000,     note: "Una cartera que cuesta más que una casa en provincia." },
      { id: "rolex",    emoji: "⌚", name: "Rolex de oro",               price: 40000,     note: "Un reloj para mirar cómo pasa el tiempo de los demás." },
      { id: "miraflores",emoji: "🏖️", name: "Casa de lujo en Miraflores (Lima)", price: 2200000, note: "Residencia frente al malecón, en el distrito más caro del Perú." },
      { id: "yate",     emoji: "🛥️", name: "Súper yate",                 price: 300000000, note: "Para sentir el agua... que a millones les falta." },
      { id: "rolls",    emoji: "🚙", name: "Rolls-Royce Phantom",         price: 500000,    note: "El auto preferido de quien nunca maneja." },
      { id: "patek",    emoji: "⏱️", name: "Reloj Patek Philippe",        price: 200000,    note: "No lo posees: solo lo cuidas para la próxima generación." },
      { id: "caballo",  emoji: "🐎", name: "Caballo de carrera pura sangre", price: 1000000, note: "Para apostar... siendo ya millonario." },
      { id: "jet",      emoji: "✈️", name: "Jet privado Gulfstream G650", price: 70000000,  note: "Contamina en una hora lo que tú en un año. Pero qué cómodo." },
    ],
  },
  {
    id: "latam",
    title: "Hecho en Latinoamérica",
    emoji: "🌎",
    blurb: "Lo que de verdad cambia una vida por aquí. Cuesta una fracción de un Ferrari.",
    items: [
      { id: "carrera",   emoji: "🎓", name: "Una carrera universitaria (Perú)", price: 30000,   note: "5 años de universidad privada. Él lo gana en ~5 segundos." },
      { id: "sueldo",    emoji: "💵", name: "Un año de sueldo peruano",         price: 5500,    note: "El trabajo de 12 meses de una persona." },
      { id: "casa",      emoji: "🏠", name: "Una casa digna en Perú",           price: 25000,   note: "Un techo de verdad para una familia." },
      { id: "comida",    emoji: "🍲", name: "Comida 1 año para una familia",    price: 4800,    note: "365 días en que nadie se acuesta con hambre." },
      { id: "startup",   emoji: "💡", name: "Iniciar una startup (EEUU)",       price: 35000,   note: "El sueño emprendedor, completo." },
      { id: "franquicia",emoji: "🍟", name: "Franquicia de comida rápida",      price: 2000000, note: "Un negocio que da empleo a todo un barrio." },
      { id: "cancer-nino",emoji: "🏥", name: "Tratar el cáncer de un niño (completo)", price: 60000, note: "Una vida que se salva con lo que él gana en ~10 segundos." },
      { id: "comedor",   emoji: "🍛", name: "Un comedor popular por 1 año",     price: 30000,   note: "Almuerzo diario para todo un barrio." },
      { id: "pozo",      emoji: "🚰", name: "Agua potable para un pueblo",      price: 20000,   note: "Un pozo y red de agua que cambian un caserío entero." },
    ],
  },
  {
    id: "mega",
    title: "Megalomanía",
    emoji: "🚀",
    blurb: "Cosas que solo se le ocurren a quien ya tiene demasiado.",
    items: [
      { id: "netflix",  emoji: "📺", name: "Netflix de por vida (70 años)",   price: 20000,        note: "Maratón eterno mientras el contador sigue subiendo." },
      { id: "steam",    emoji: "👾", name: "TODOS los juegos de Steam",       price: 1900000,      note: "Los +100,000 juegos. No te alcanzaría la vida para jugarlos." },
      { id: "satelite", emoji: "🛰️", name: "Lanzar tu propio satélite",       price: 1000000,      note: "Tu cara orbitando la Tierra. ¿Por qué no?" },
      { id: "espacio",  emoji: "🌌", name: "Un viaje turístico al espacio",   price: 450000,       note: "Ver lo pequeño que es todo... incluyéndote a ti." },
      { id: "superbowl",emoji: "📣", name: "Anuncio en el Super Bowl (30s)",  price: 7000000,      note: "Medio minuto de fama por el precio de 250 casas." },
      { id: "mundial",  emoji: "🏆", name: "TODAS las entradas a la final del Mundial", price: 80000000, note: "Un estadio lleno, todo a tu nombre." },
      { id: "isla",     emoji: "🏝️", name: "Una isla privada",               price: 50000000,     note: "Tu propio pedazo de planeta, sin vecinos." },
      { id: "pelicula", emoji: "🎬", name: "Producir una película de Hollywood", price: 100000000, note: "Con superhéroes y todo. Pagada de un bolsillo." },
      { id: "monalisa", emoji: "🖼️", name: "Comprar la Mona Lisa",           price: 850000000,    note: "El cuadro más valioso del mundo, colgado en tu sala." },
      { id: "f1",       emoji: "🏁", name: "Un equipo de Fórmula 1 (1 temporada)", price: 200000000, note: "Correr en círculos, pero en serio." },
      { id: "rascacielos",emoji: "🏙️", name: "Construir tu propio rascacielos", price: 850000000, note: "Tu nombre escrito en el cielo de la ciudad." },
      { id: "gta",      emoji: "🎮", name: "Producir GTA VI (el juego más caro)", price: 2000000000, note: "El videojuego más costoso de la historia." },
      { id: "gpus",     emoji: "🖥️", name: "1 millón de GPUs Nvidia H100",    price: 30000000000,  note: "Para entrenar una IA que le diga que es un genio." },
    ],
  },
  {
    id: "importa",
    title: "Lo que de verdad importa",
    emoji: "❤️",
    blurb: "Y aquí está lo incómodo: todo esto cabe en su bolsillo.",
    items: [
      { id: "pobreza-pe", emoji: "🇵🇪", name: "Sacar de la pobreza a todo el Perú (1 año)", price: 9000000000,   note: "~9 millones de personas, un año entero. (estimado)" },
      { id: "casas-pe",   emoji: "🏘️", name: "Casa para todos los sin techo del Perú",     price: 36000000000,  note: "Cerrar el déficit habitacional del país. (estimado)" },
      { id: "deuda-pe",   emoji: "📉", name: "Pagar la deuda externa del Perú",            price: 80000000000,  note: "Un país entero, libre de deuda. (estimado)" },
      { id: "hambre",     emoji: "🍞", name: "Acabar con el hambre en el mundo (1 año)",   price: 40000000000,  note: "La ONU estima ~40 mil millones al año. Le sobra." },
      { id: "pobreza-w",  emoji: "🌍", name: "Sacar de la pobreza extrema al mundo (1 año)", price: 175000000000, note: "Sí. Una sola persona podría intentarlo." },
      { id: "gaza",       emoji: "🕊️", name: "Reconstruir Gaza",                          price: 53000000000,  note: "~$53 mil millones para levantarla, según la ONU y el Banco Mundial (2025)." },
      { id: "ucrania",    emoji: "🇺🇦", name: "Reconstruir Ucrania",                       price: 524000000000, note: "Lo que el Banco Mundial calcula para levantar el país (2025)." },
      { id: "la-fires",   emoji: "🔥", name: "Reconstruir Los Ángeles tras los incendios", price: 50000000000,  note: "El fuego de enero de 2025 arrasó barrios enteros." },
      { id: "cancer-i",   emoji: "🎗️", name: "Financiar 10 años de investigación del cáncer", price: 72000000000, note: "Acelerar la cura que millones esperan." },
      { id: "malaria",    emoji: "🦟", name: "Erradicar la malaria del mundo (1 año)",     price: 6000000000,   note: "Una enfermedad que aún mata a un niño cada minuto." },
      { id: "agua-w",     emoji: "💧", name: "Agua potable para todo el mundo (1 año)",    price: 114000000000, note: "Acceso a agua limpia y saneamiento para todos. (ONU)" },
    ],
  },
  {
    id: "imperio",
    title: "Comprar el mundo",
    emoji: "🏦",
    blurb: "Cuando el dinero deja de comprar cosas y empieza a comprar clubes, empresas… y hasta personas.",
    items: [
      { id: "alianza",     emoji: "⚪", name: "Club Alianza Lima",            price: 40000000,      note: "El equipo de La Victoria, comprado entero. (valor estimado)" },
      { id: "universitario",emoji: "🟡", name: "Club Universitario de Deportes", price: 45000000,   note: "La 'U' y su estadio Monumental. (valor estimado)" },
      { id: "epstein",     emoji: "🏝️", name: "La isla de Epstein",          price: 60000000,      note: "Little Saint James, vendida en 2023 por ~$60 millones." },
      { id: "alicorp",     emoji: "🏭", name: "Alicorp (empresa peruana)",    price: 1500000000,    note: "Las marcas que están en tu cocina todos los días." },
      { id: "nba",         emoji: "🏀", name: "Un equipo de la NBA",          price: 4000000000,    note: "Tu propia franquicia de básquet, con cancha y todo." },
      { id: "barca",       emoji: "🔵", name: "FC Barcelona",                 price: 5600000000,    note: "Más que un club. Y ahora, tuyo." },
      { id: "trump",       emoji: "🇺🇸", name: "La fortuna de Donald Trump",  price: 6500000000,    note: "Todo su imperio, según Forbes (2025)." },
      { id: "real",        emoji: "⚽", name: "El Real Madrid",               price: 6600000000,    note: "El club de fútbol más valioso del mundo." },
      { id: "credicorp",   emoji: "🏦", name: "Credicorp (dueña del BCP)",    price: 18000000000,   note: "El banco más grande del Perú. Comprado." },
      { id: "x",           emoji: "🐦", name: "Comprar X (Twitter) otra vez", price: 44000000000,   note: "Ya lo hizo una vez. Por aburrimiento." },
      { id: "slim",        emoji: "💰", name: "La fortuna de Carlos Slim",    price: 100000000000,  note: "El hombre más rico de Latinoamérica, comprado." },
      { id: "gates",       emoji: "🧠", name: "La fortuna de Bill Gates",     price: 110000000000,  note: "Todo lo del cofundador de Microsoft." },
      { id: "spotify",     emoji: "🎵", name: "Spotify (entero)",             price: 130000000000,  note: "Toda la música del mundo, tuya." },
      { id: "netflix-co",  emoji: "🎬", name: "Netflix (la empresa entera)",  price: 400000000000,  note: "No la suscripción: la compañía completa." },
      { id: "google",      emoji: "🔍", name: "Google (Alphabet)",            price: 2200000000000, note: "Buscador, YouTube, Android, Gmail… todo tuyo." },
      { id: "microsoft",   emoji: "🪟", name: "Microsoft",                    price: 3300000000000, note: "Windows, Office, Xbox y media nube del planeta." },
      { id: "nvidia",      emoji: "🟩", name: "Nvidia",                       price: 3500000000000, note: "La fábrica de los chips que mueven la IA." },
      { id: "apple",       emoji: "🍎", name: "Apple (toda la empresa)",      price: 3500000000000, note: "Ups… cuesta MÁS que su fortuna. Espera a que suba el contador 😏" },
    ],
  },
];

// --- Frases de Elon cuando NO te alcanza (compra bloqueada) -------
// Sarcásticas, divertidas y con un poquito de conciencia.
const ELON_DISS = [
  "Ni yo tengo tanto… y eso que vendí Twitter por capricho. 🙄",
  "Eso cuesta MÁS que toda mi fortuna. Y mira que es enorme. 💅",
  "Calma: Tesla ya perdió contra BYD, no me pidas milagros. 🚗💨",
  "Error 404: fortuna suficiente no encontrada.",
  "Hasta el hombre más rico del mundo tiene un límite. Uno solo, pero lo tiene.",
  "Pa' comprar eso espera a que suba el contador… unos 3.000 añitos. ⏳",
  "No, jefe. Eso ni regalando Starlink de paquete.",
  "¿Sabes qué SÍ alcanzaría? Darle de comer a un país. Pero tú quieres chips. 🤷",
  "Esa no. Ni inflando mis acciones otra vez.",
  "Ser trillonario no es comprarlo TODO… es que millones no tengan nada. 😬",
  "Por menos compré Twitter entero. Y mira lo bien que me fue. 🐦",
  "Eso ni con 'funding secured'. Y ya sabes cómo terminó esa. 💸",
  "Tranquilo, te alcanza… el año que viene. Como el Full Self-Driving. 🚗",
  "Ni vendiendo todos los Cybertruck que se oxidaron me da. 🛻",
  "Eso cuesta más que llevar gente a Marte. Y eso ya es decir mucho. 🚀",
  "No me alcanza. Igual que no me alcanzó la paciencia con los de Twitter. ✂️",
  "Por ese precio mejor lanzo otro auto al espacio y listo. 🛰️",
  "Eso ni con todo lo que 'gané' tuiteando Dogecoin. 🐶📉",
  "Pa' eso tendría que trabajar 420 horas a la semana. Y solo hago 410. 😮‍💨",
  "Ni mi robot Optimus (o sea, el señor del disfraz) puede pagar eso. 🤖",
  "No alcanza. Pero oye, ¿ya viste mi perfume 'Pelo Quemado'? 🔥",
  "Eso es más caro que cambiarle el nombre a todo por una sola letra: X. ✖️",
  "Imposible. Y eso que cobro $8 por una palomita azul. ☑️",
  "Ni con el sueldo de 1 billón que me aprobó la junta. Qué humilde soy. 💼",
  "Caro. Casi tanto como mi ego. Casi. 😎",
  "Eso ni metiéndole un chip al cerebro a otro monito. 🐒🔌",
  "Por ese precio mejor te cavo un túnel. The Boring Company saluda. 🕳️",
  "No me alcanza, pero te lo prometo 'el próximo año'. Como el Roadster. 🏎️",
  "Eso cuesta más que mis disculpas. Y yo nunca me disculpo. 🙃",
  "Tranqui: el resultado más entretenido es el más probable… menos comprar eso. 🎭",
  "Ni con todas las palomitas azules canceladas de golpe. ☑️❌",
  "Eso es plata de verdad. Yo manejo plata de PowerPoint. 📊",
  "No alcanza. Pregúntales a los anunciantes a los que mandé… saludos. 👋",
  "Por menos me encargo de 'la eficiencia del gobierno'. Y mira el resultado. 🏛️",
  "Eso ni tuiteando a las 3am cosas de las que me arrepiento. 📱",
  "Caro. Como mantener prometido un robotaxi desde 2019. 🚕",
  "No me da. Pero recuerda mi consejo: 'tengan más hijos'. Eso sí es gratis. 👶",
  "Eso supera mi fortuna y mi capacidad de fingir humildad. 🎩",
  "Imposible. Mejor pongo una encuesta en X y que decidan los bots. 🤖🗳️",
  "Ni vendiendo lanzallamas 'que técnicamente no son lanzallamas'. 🔥",
  "Eso es mucho hasta para quien compró un pajarito por 44 mil millones. 🐦",
  "No alcanza. Y eso que me hago llamar 'Technoking'. 👑",
  "Por ese precio armo otra red social y la rompo en un mes. 📉",
  "Caro. Tanto que ni Grok me inventa una excusa mejor. 🤓",
  "Eso ni fumándome la calma en vivo otra vez. 🚬",
  "No me da. La riqueza 'gotea', dicen. A mí me llovió encima. ☔",
  "Eso cuesta más que un hospital. Pero un hospital no luce en una fiesta. 🏥",
  "Imposible. Ese dinero alimentaría a una ciudad. Pero tú querías un juguete. 🧸",
  "No alcanza. Y sí, podría acabar una hambruna en su lugar. Detalles. 🍞",
  "Eso es más que la deuda de tu país. Que, de paso, también podría pagar. 📉",
  "Caro. Como las cosas que prometí 'para 2020' y seguimos esperando. 📅",
  "Ni con todos mis tuits borrados justo a tiempo. 🫥",
  "No me da, pero sigue soñando. Yo soñé con Marte y aquí seguimos. 🔴",
  "Eso supera mi fortuna. Sabes qué no la supera: la indiferencia. 😶",
  "Por menos compré un buen lío legal con la SEC. 👨‍⚖️",
  "No alcanza. Igual mañana 'valgo' otros 50 mil millones por un tuit. 📈",
  "Caro. Tanto como ponerle a mi hijo 'X Æ A-12'. 👶",
  "Eso ni con el bono más absurdo aprobado en la historia corporativa. 💰",
  "No me da. Pero descuida, le echo la culpa a los empleados. ✂️",
  "Imposible. Mejor te vendo una palomita azul y nos hacemos los felices. ☑️",
  "Eso cuesta más que mi humildad… que vale exactamente cero. 🆓",
  "No alcanza, pero seguro la culpa es del 'wokismo'. Siempre lo es. 🙄",
  "Caro. Como prometer 'comedia legal' y luego vetar a quien me critica. 🤐",
  "Ese precio ni con Starman dando vueltas eternas allá arriba. 👨‍🚀",
  "No me da. Pero mira: una sola persona casi compra el planeta. Casi. 🌎",
  "Eso es más que varios PIB juntos. Y lo tiene UNA persona. Piénsalo. 🧠",
  "Imposible. Aunque, seamos honestos, nadie 'gana' tanto solo. 👷",
  "No alcanza. Y eso debería preocuparte más que emocionarte. ⚠️",
  "Caro. Tanto que avergonzaría a cualquiera con vergüenza. Yo no tengo. 😬",
  "Eso ni reabriendo la fábrica en plena pandemia 'porque sí'. 🏭",
  "No me da. Pero relájate: mi contador sube solo. El tuyo, no. 📊",
  "Imposible. Tú trabajas 40 años; yo subo eso en lo que dura un café. ☕",
  "Eso es de otro nivel. El nivel de '¿por qué una persona tiene tanto?'. ❓",
  "No alcanza. Ni con todos mis bots 'geniales' dándome like. 🤖❤️",
  "Caro. Tan caro que hasta yo digo: esto no debería ser legal. 💸",
];

// --- Frases para el recibo: cómo se tiene TANTO dinero -----------
// Entretenidas pero con conciencia social. Se muestra UNA al azar.
const RECEIPT_LINES = [
  "Con lo que gastaste, miles de familias comerían un año. Pero qué lindo tu yate. 🛥️",
  "Nadie amasa un millón de millones solo. Pregúntale a quien arma tus autos. 🔧",
  "La mitad del planeta vive con menos de $7 al día. Él los gana ~900 veces… por segundo. ⏱️",
  "Una persona no necesita un millón de millones. Un millón de personas, sí. 🌍",
  "El dinero no sale de la nada: alguien, en algún lugar, lo produjo por muy poco. 👷",
  "Si trabajaras desde la época de los faraones, aún no tendrías lo que él gana este año. 🏺",
  "No es magia ni genialidad: es un sistema que premia tener para tener más. ♻️",
  "Gastaste una fortuna entera… y la suya ni se enteró. 😅",
  "Su fortuna no cabe en este recibo. La desigualdad, tampoco. 🧾",
  "Podrías pagar el sueldo de por vida de un pueblo entero. O comprar un reloj. Tú decides. ⌚",
  "Lo que ganó mientras leías esto ya pagó la cena de una familia. La tuya, quizás. 🍽️",
  "Ser el más rico del mundo no es un logro: es una estadística incómoda. 📊",
  "El hambre del mundo se acaba con 40 mil millones al año. A él le sobra para 20 años. 🍞",
  "Riqueza extrema y pobreza extrema no son accidentes: son la misma moneda. 🪙",
  "Cada segundo que pasa, él gana lo que tú en una semana. Y no movió un dedo. 🛋️",
  "Compraste clubes, islas y empresas. Su fortuna apenas bostezó. 😴",
  "Un trillón en billetes de $100 pesaría como 10 mil autos. Y aún seguiría subiendo. 🚗",
  "Lo importante no es cuánto compraste, sino lo poco que a él le dolió. 💸",
  "Mientras decides qué comprar, alguien decide si come hoy. ⚖️",
  "El esfuerzo no te hace trillonario. Si así fuera, tu mamá tendría tres planetas. 🪐",
  "La caridad de los ultra-ricos es una propina. El sistema es el verdadero negocio. 🎩",
  "Podrías sacar de la pobreza a un país antes del almuerzo. Pero compraste un Ferrari. 🏎️",
  "Su patrimonio creció más en un día que lo que ganarás en mil vidas. 🔁",
  "No te hicieron pobre por flojo, ni a él rico por listo. Te hicieron creer eso. 🧠",
  "El primer trillonario del mundo y aún hay quien duerme en la calle. ¿Casualidad? 🏚️",
  "Con su fortuna se duplicaría el presupuesto de salud de varios países. Imagina. 🏥",
  "Los súper ricos no guardan el dinero bajo el colchón: lo guardan donde no paga impuestos. 🏝️",
  "Tú redondeas a la baja en la tienda. Él redondea países. 🌎",
  "Lo que para ti es 'toda una vida de trabajo', para él es un café entre reuniones. ☕",
  "El verdadero superpoder no es volar: es no pagar lo que debería. 🦸",
  "Si la riqueza goteara, ya estaríamos todos empapados. Llevamos décadas esperando. 💧",
  "Compraste la Mona Lisa y a Bill Gates. Su cuenta apenas parpadeó. 👁️",
  "Cada minuto suyo vale 827 sueldos peruanos. Cada minuto tuyo vale… tu minuto. 🇵🇪",
  "El dinero es energía: la suya la generaron millones de manos invisibles. ✋",
  "Ningún esfuerzo humano explica esta cifra. Solo un sistema diseñado así. 🏗️",
  "Rompiste tu récord de gasto. Él rompió el de acumulación. Hace rato. 🏆",
  "Lo que él dona para la foto, otros lo necesitan para vivir. 📸",
  "Un hospital cuesta menos que su jet privado. Adivina qué hay más. ✈️",
  "Si contaras su fortuna a $1 por segundo, terminarías en más de 30 mil años. ⏳",
  "La pobreza no es falta de dinero en el mundo. Es exceso de él en pocas manos. 🤲",
  "Compraste media tecnología del planeta. Su fortuna ni se despeinó. 💇",
  "El mérito existe. Pero el mérito no construye yates de 300 millones. 🛥️",
  "Mientras gastas en lujos, recuerda: alguien limpió esa fortuna por el sueldo mínimo. 🧹",
  "Su 1% perdido hoy alimentaría a más gente que toda tu ciudad. 🏙️",
  "El cuento del 'hombre hecho a sí mismo' siempre olvida a quienes lo hicieron. 📖",
  "Gastar su dinero es fácil. Lo difícil es entender por qué lo tiene todo él. 🤔",
  "No le tengas envidia: tenle preguntas. ¿De dónde salió cada dólar? ❓",
  "Con lo que gana en una semana, una escuela entera estudiaría una década. 🎓",
  "El planeta tiene recursos para todos. Solo que unos pocos se sirvieron primero. 🍽️",
  "Acabas de simular ser trillonario. Millones simulan llegar a fin de mes. 📅",
  "La diferencia entre tú y él no es el esfuerzo. Es de dónde partió cada uno. 🏁",
  "Su fortuna paga la deuda de varios países. Pero, oye, qué bonito tu nuevo reloj. ⌚",
];
